### PR TITLE
add fuzz test for cockroach/parser

### PR DESCRIPTION
**Pull request by tbg**

### CODE REVIEW

**Comment by tbg** [comment]
the first commit is a verbatim copy of autogenerated stuff. Only f85340b is interesting.

**Comment by tamird** [comment]
Is doing this as a fork of go-fuzz the right thing? I was imagining a repo containing only the necessary bits and depending on upstream.

**Comment by tbg** [comment]
that works too, but I'm going to PR this upstream and so this is more comfortable for now.

**Comment by tamird** [comment]
LGTM

**Comment by tbg** [comment]
> but should it be?

it could be. Talked to @petermattis about this before, and could just add that as a check in `Parse()`.

**Pull request merged**
