### PR TITLE
Fix Parser example and add new inputs to corpus

### PR DESCRIPTION
**Pull request by nvb**
This required removing `Expr` evaluation, which now requires TypeChecking.

### CODE REVIEW

**Comment by tbg** [comment]
While you're add it, add a `.gitattributes` with `-diff` for the corpus.

**Comment by tbg** [comment]
(I can't look at this through github because it doesn't even manage to show the interesting changes)

**Comment by nvb** [comment]
Done, although it doesn't look like the `.gitattributes` is applying on Github (it is locally).

**Comment by tbg** [comment]
Better late than never -- LGTM! 😄

**Pull request merged**
